### PR TITLE
Ensure compilability

### PR DESCRIPTION
**Pull request by luedi**

### CODE REVIEW

**Comment by rjperes** [comment]
The problem is that those DLLs, almost for sure, cannot be distributed freely.
I already had them, of course, but had to remove them from the source.
Will try to contact the owner to see if they can be distributed.

**Comment by rjperes** [comment]
I contacted Devart, DevComponents and ActiPro so as to find out their availability to let us distribute their DLLs with Visual NHibernate. As soon as I have answers, I will let you know through the mailing lists.

**Comment by rjperes** [comment]
ActiPro authorized the distribution of their DLLs.

**Comment by sbohlen** [comment]
Excellent work -- one down, a few more to go!

Steve Bohlen
sbohlen@gmail.com
http://blog.unhandled-exceptions.com
http://twitter.com/sbohlen

**Comment by luedi** [comment]
Good news about ActiPro. Is there a chance that you provide a copy of the registered Actipro dll's for me? I can't start the application without them. Meanwhile i removed the licensing stuff but i can't test it.

**Comment by rjperes** [comment]
You can get a working version from http://www.slyce.com/VisualNHibernate/index.html.

**Comment by luedi** [comment]
i've done it already, but i can't debug the application with this. Maybe i just need the license.licx file to get it work?

**Comment by luedi** [comment]
Some sourcecode seems to be missing. There is a dll called NHibernate.AAT.dll in the Templates folder. I have decompiled it with DotPeek and could see, that it uses some ArchAngel dll's. It is called by reflection from the workbench. As i removed the signing of the ArchAngel dll's (you didn't provide the key) NHibernate.AAT.dll could not be loaded because it's also signed with Slyce's key.

**Comment by rjperes** [comment]
That DLL is included in this pull request. It belongs to Slyce, so it can be distributed.

**Comment by luedi** [comment]
You are right, but the dll is compiled against versions of ArchAngel.Interfaces.dll and ArchAngel.NHIbernateHelper.dlls which have a strong name and therefor they can't be loaded. NHibernate.AAT.dll seems to be generated by the ArchAngel framework. My decompiled dll do not work correct. It try to load an embedded resource "options.xml" which fails for some reason.

Is there any documentation from Slyce how to generate this dll correct?

How do you compile and debug the application?

**Pull request closed without merging**
